Update pdf & tex
jasonwalker80/cse427s pull request #21
Opened 2017-10-22 20:07 UTC by bob-skowron

answers for 1, 2, and part of 3 started

2017-10-24 16:48 UTC, jasonwalker80 requested changes
still reviewing 2 and 3. Only comment on 1 is a potential typo.

2017-10-24 16:48 UTC, jasonwalker80 commented on hw7/HW7.tex
> +			Code to add to driver: \textit{gob.setInputFormatClass(KeyValueTextInputFormat.class}\\
typo, 'gob' => 'job'

2017-10-26 01:46 UTC, jasonwalker80 commented on hw7/HW7.tex
> +		\item[c.] Mapper output for lines from Hamlet:\\
I'm assuming the question is intended for us to use the toy example. 

The actual lines from the files are:
```
hamlet:282	Have heaven and earth together demonstrated
hamlet:1375	There are more things in heaven and earth, Horatio,
```

2017-10-26 01:47 UTC, jasonwalker80 commented on hw7/HW7.tex
> +		\item[a.] Cosine similarity: $\frac{r_{x}^{T}\cdot r_{y}}{\parallel r_{x} \parallel \cdot \parallel r_{y} \parallel}$\\
I'm trusting you on the math sections @bskowron23. Looks good to me!

2017-10-26 01:52 UTC, jasonwalker80 commented on hw7/HW7.tex
> +				\item An advantage of normalization is to remove bias. We can remove users who are overly critical (all low scores) or overly enthusiastic (all high rankings)
Another advantage is that the cosine similarity improves. This normalization is what makes cosine = pearson.

Relevant lines from slides:
```
Normalizing (subtracting the user’s mean rating)
• remove bias (enthusiastic vs overly critical user)
• improves cosine similarity measure
• now cosine similarity = Pearson correlation
```

Relevant section from text:
```
If we normalize ratings, by subtracting from each rating the average rating of that user, we turn low ratings into negative numbers and high ratings into positive numbers. If we then take the cosine distance, we find that users with opposite views of the movies they viewed in common will have vectors in almost opposite directions, and can be considered as far apart as possible. However, users with similar opinions about the movies rated in common will have a relatively small angle between them.
```

2017-10-26 01:55 UTC, jasonwalker80 commented on hw7/HW7.tex
> +		\item[c.] One disadvantage of the Jaccard similarity is that it does not take into account the value of the rating. Thus, even if two users rate the exact same items with opposite ratings it would
One example from the text and slides is to "round" the data, ex. [1,2] = 0 [3,4,5] = 1

From the text:
```
We could try to eliminate the apparent similarity between movies a user rates highly and those with low scores by rounding the ratings. For instance, we could consider ratings of 3, 4, and 5 as a “1” and consider ratings 1 and 2 as unrated.
```

2017-10-26 02:03 UTC, jasonwalker80 commented on hw7/HW7.tex
> +				\item With Pearson correlation you need to compute and store the average rating for each user. This requires us to process the entire set of ratings.
"Normalization requires that you compute and store the average rating for each user. This compute and storage of mean values must be performed each time the ratings change and requires preprocessing the entire set of ratings each time it changes."

2017-10-26 02:12 UTC, jasonwalker80 commented on hw7/HW7.tex
> +		\item[a.] The dual approach can be more efficient if the \#users $\gg$ \#items. Also, it can be easier to find similar items.
"Also, it's easier to find similar items since items typically belong to a specific genre, ex. 60's rock versus 1700's baroque. It's more common for users to like items from different genres."

2017-10-26 02:14 UTC, jasonwalker80 commented on hw7/HW7.tex
> +			((movie3,movie5), (3,5))\\
Are we missing : `((movie2,movie5), (2,5))` from user2?

2017-10-26 02:16 UTC, jasonwalker80 commented on hw7/HW7.tex
> +			((movie3,movie5), (3,5))\\
Same as above, might be missing `((movie2,movie5), (2,5))`

2017-10-26 02:18 UTC, jasonwalker80 reviewed
A few comments, suggestions and example answers to add in for 2 and 3.

2017-10-26 02:50 UTC, bob-skowron commented
All comments should be covered in latest commit straight to master.

2017-10-26 02:50 UTC, closed without merging